### ISSUE TITLE
User and password

### ISSUE THREAD

**Issue by adamadiarra** [webmaxru/mqtt-websockets-angular-pwa#1]
How can I use the user and the password?
Because i use cloudmqtt.

**Comment by webmaxru** [comment]
Hello!
I think this is a bit irrelevant repo for your case, because this is just a frontend with very generic communication with the backend (where I use MQTT) via websockets.
I recommend you to have a look at this example: https://www.cloudmqtt.com/docs/nodejs.html

**Comment by adamadiarra** [comment]
> 
> 
> Hello!
> I think this is a bit irrelevant repo for your case, because this is just a frontend with very generic communication with the backend (where I use MQTT) via websockets.
> I recommend you to have a look at this example: https://www.cloudmqtt.com/docs/nodejs.html

Okay, i understand now. But i have a question.  is it a good idea to do a backend and frontend to use mqtt?

**Comment by webmaxru** [comment]
I'd use MQTT on the backend part only. If you want to stream the data MQTT<->Backend<->Frontend - just use websockets channel between back and front
